name: Publish to npm
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest

    environment: npm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/
        
      - name: Ensure no npm token auth is present
        run: |
          echo "Checking for injected npm auth..."
          npm config delete //registry.npmjs.org/:_authToken || true
          rm -f ~/.npmrc || true
          rm -f "$NPM_CONFIG_USERCONFIG" || true
          rm -f /home/runner/work/_temp/.npmrc || true
          npm config list

      - name: Install
        run: npm install
          
      - name: Publish
        run: npm publish --access public --provenance
